In [9]:
import pandas as pd
import numpy as np

df = pd.read_csv('supermarket_sales.csv')
n = 10

In [10]:
# Mengasumsikan 'City' adalah kolom yang benar
df["City"] = df["City"].astype("string")

# Mengambil data Unit Price dan Quantity dari DataFrame ke dalam np.array
unit_price = df['Unit price'].to_numpy()
quantity = df['Quantity'].to_numpy()

# Melakukan operasi penjumlahan, pengurangan, perkalian, dan pembagian dengan np.array
penjumlahan = unit_price + quantity
pengurangan = unit_price - quantity
perkalian = unit_price * quantity

# Pastikan tidak ada pembagian oleh nol
pembagian = np.divide(unit_price, quantity, out=np.zeros_like(unit_price), where=quantity!=0)

print("\nOperasi Aritmatika menggunakan Data Unit Price dan Quantity di Seluruh DataFrame (10 Data Pertama)")
print("\nPenjumlahan")
print(penjumlahan[:n])
print("\nPengurangan")
print(pengurangan[:n])
print("\nPerkalian")
print(perkalian[:n])
print("\nPembagian")
print(pembagian[:n])


Operasi Aritmatika menggunakan Data Unit Price dan Quantity di Seluruh DataFrame (10 Data Pertama)

Penjumlahan
[81.69 20.28 53.33 66.22 93.31 92.39 74.84 83.56 38.26 57.84]

Pengurangan
[67.69 10.28 39.33 50.22 79.31 78.39 62.84 63.56 34.26 51.84]

Perkalian
[522.83  76.4  324.31 465.76 604.17 597.73 413.04 735.6   72.52 164.52]

Pembagian
[10.67        3.056       6.61857143  7.2775     12.33       12.19857143
 11.47333333  7.356      18.13       18.28      ]


In [11]:
# Hasil data matrix array hanya 1 dimensi

tup = unit_price.reshape(-1, 1).astype(int)
tq = quantity.reshape(-1, 1).astype(int)
print("\nTranspose dari Data Unit Price ")
print(tup[:n])
print("\nTranspose dari Data Quantity ")
print(tq[:n])

rsup = unit_price.reshape(-1, 1).astype(int)
rsq = quantity.reshape(-1, 1).astype(int)
print("\nReshape dari Data Unit Price ")
print(rsup[:n])
print("Reshape dari Data Quantity ")
print(rsq[:n])

fup = unit_price.flatten().astype(int)
fq = quantity.flatten().astype(int)
print("\nFlatten dari Data Unit Price ")
print(fup[:n])
print("\nFlatten dari Data Quantity ")
print(fq[:n])



Transpose dari Data Unit Price 
[[74]
 [15]
 [46]
 [58]
 [86]
 [85]
 [68]
 [73]
 [36]
 [54]]

Transpose dari Data Quantity 
[[ 7]
 [ 5]
 [ 7]
 [ 8]
 [ 7]
 [ 7]
 [ 6]
 [10]
 [ 2]
 [ 3]]

Reshape dari Data Unit Price 
[[74]
 [15]
 [46]
 [58]
 [86]
 [85]
 [68]
 [73]
 [36]
 [54]]
Reshape dari Data Quantity 
[[ 7]
 [ 5]
 [ 7]
 [ 8]
 [ 7]
 [ 7]
 [ 6]
 [10]
 [ 2]
 [ 3]]

Flatten dari Data Unit Price 
[74 15 46 58 86 85 68 73 36 54]

Flatten dari Data Quantity 
[ 7  5  7  8  7  7  6 10  2  3]


In [12]:
print("\nJumlah data unit price (10 data pertama)")
print("Nilai Minimal:", np.min(unit_price[:n]))
print("Nilai Maksimal:", np.max(unit_price[:n]))
print("Nilai Rata-rata:", np.mean(unit_price[:n]))
print("Total Nilai:", np.sum(unit_price[:n]))
print("Standar Deviasi:", np.std(unit_price[:n]))

print("\nJumlah data quantity (10 data pertama)")
print("Nilai Minimal:", np.min(quantity[:n]))
print("Nilai Maksimal:", np.max(quantity[:n]))
print("Nilai Rata-rata:", np.mean(quantity[:n]))
print("Total Nilai:", np.sum(quantity[:n]))
print("Standar Deviasi:", np.std(quantity[:n]))


Jumlah data unit price (10 data pertama)
Nilai Minimal: 15.28
Nilai Maksimal: 86.31
Nilai Rata-rata: 59.972
Total Nilai: 599.72
Standar Deviasi: 21.435495235706593

Jumlah data quantity (10 data pertama)
Nilai Minimal: 2
Nilai Maksimal: 10
Nilai Rata-rata: 6.2
Total Nilai: 62
Standar Deviasi: 2.227105745132009
